#ifndef TORTOISE_SESSION_HPP
#define TORTOISE_SESSION_HPP

#include <memory>
#include <mutex>
#include <thread>
#include <vector>

#include "event.hpp"
#include "torrent.hpp"

namespace tortoise
{
    /// \brief A session manages a collection of torrents.
    class Session
    {
    public:
        /*! \brief Creates a new session.
         *  \param callbacks Callbacks for events generated by the session, these are optional and may be empty if the user is not interested in them.
         */
        Session(event::Callbacks callbacks);
        ~Session();

        /*! \brief Adds a torrent to the session.
         *  \param torrent Parameters for the the new torrent.
         *  \return A handle to the torrent.
         */
        TorrentHandle AddTorrent(TorrentParameters parameters);

        /*! \brief Removes a torrent from the session. If the torrent is not in the session, this function has no effect.
         *         This function may block.
         *  \param handle handle to the torrent.
         */
        void RemoveTorrent(TorrentHandle handle);

        /*! \brief Pop all events and process them using the given callbacks, this function is expected to be called regularly.
         *  Note that only events that are enabled in the session will be generated.
         */
        void HandleEvents();

        // Disable copy and move.
        Session(const Session &) = delete;
        Session(Session &&) = delete;
        Session &operator=(const Session &) = delete;
        Session &operator=(Session &&) = delete;

    private:
        class Implementation;
        std::unique_ptr<Implementation> implementation_;
    };
}

#endif